### ISSUE TITLE
Make sure to check the capitalization

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/OM10#4]
I should change all the uppercase magnitudes to the lowercase magnitudes. Line 6 does not change that -- I should change plotting.py.

**Comment by jennykim1016** [comment]
For [this](http://iopscience.iop.org/article/10.1088/0004-637X/777/2/97/meta#apj485108t5) paper, the magnitudes are in CFHT, but they could easily be converted to SDSS magnitudes by considering offsets of zeropoints. [This](http://terapix.iap.fr/article.php?id_article=713) seems to contain some useful information.

**Comment by drphilmarshall** [comment]
Nice catch, Jenny. Looks like those 0.05 mag corrections are small enough
to ignore to first order, would you say?

**Comment by jennykim1016** [comment]
Yes, I will ignore the discrepancies. Thanks!

**Comment by jennykim1016** [comment]
1) In addition to this, for QuasarColorComparison, I should fix OM10 to make it read the .csv or .txt data as well. Currently, it just allows me to read .fits data.
If that is too much, I can just set the constructor equal to the input data in the body of the notebook.

2) The style for `Alessandro et al.` notebook needs some improvements. I should write comments and improve the readability. 

Edit : Everything resolved. Closing the issue.
