### ISSUE TITLE
Fix Reweighting algorithm

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/OM10#6]
The `gaussian_reweight` method does not calculate the weight properly; I should fix it so that the mean of the redshift in OM10 lenses matches that of LRGs.

**Comment by jennykim1016** [comment]
Normalizing the histogram has no problem as of now, but the weighting still has problem. Especially,

`fig1 = corner.corner(features, labels=labels, color='blue', weight=True, smooth=1.0, hist_kwargs=dict(normed=True))`
`fig2 = corner.corner(features, labels=labels, color='blue', smooth=1.0, hist_kwargs=dict(normed=True))`

the resulting cornerplots from those two lines are identical. Rejection sampling did not make any difference. It might be great to investigate the `corner()` function call and the method itself.

**Comment by drphilmarshall** [comment]
I think `weight` has to be set to a numpy array of the same length as the
features array, so that each sample gets a weight. I'm surprised the corner
code runs when you pass it just a single boolean!

Test: if you plot your weights against their feature (eg `sample['ZLENS']`)
values using `plt.plot()`, you should see them lie underneath an envelope
whose shape you derived...

**Comment by jennykim1016** [comment]
Oh, if I run the code above, as you pointed out, it might not run. That is not a real code that I have been using -- the real code that I've been using is either
`fig1 = om10.plot_figure(features, labels=labels, color='blue', weight=True, smooth=1.0, hist_kwargs=dict(normed=True))` 
or 
`fig1 = corner.corner(features, labels=labels, color='blue', weights=db.sample['weight'], smooth=1.0, hist_kwargs=dict(normed=True))`. Thank you for pointing out though!

**Comment by jennykim1016** [comment]
Before using the reweighting algorithm, the graph looks like the following.
![reweight before](https://cloud.githubusercontent.com/assets/18297066/22730844/679344ca-ed9d-11e6-839d-5d28203c4bad.png)
After using the reweighting algorithm, the graph looks like the following.
![reweight after](https://cloud.githubusercontent.com/assets/18297066/22730850/6f572ffa-ed9d-11e6-9e04-1928dbc8a769.png)

We need to check two things in this cornerplot :
1. The blue histogram of redshift(z) looks like a gaussian distribution whose mean is similar as the red histogram.
2. Because we are reweighting *with respect to z*, the shape of the other histograms beside the redshift one should not change.

I used both rejection sampling and general reweighting to do so, and I am pretty convinced that the current code is doing the right weighting. It might be good to check few more things - means and standard deviation of weighted lenses and quasars - but the z histogram looks promising.
