### ISSUE TITLE
Overwrite `qso_mock.fits`

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/OM10#7]
I should overwrite `qso_mock.fits` file so that it contains the columns of synthetically colored magnitudes. This will save a lot of computation time.

**Comment by drphilmarshall** [comment]
For now, you can just make a new file, `qso_mock_ugrizy.fits` that contains
ugrizy magnitudes of the lens galaxies and source qsos. Once it's validated
we can check it in - but not before!

**Comment by jennykim1016** [comment]
Oh, I checked your comment just now. I saved in a new file, `qso_mock_colored.fits`. In addition, db.py threw an error whenever I wanted to right down the db.sample data to .fits file using `writeto` method. It was because db.sample was not in a form of numpy array(rather, it was in the form of astropy.table), so I added one line where I change db.sample to the numpy array before saving it.

**Comment by drphilmarshall** [comment]
Interesting. Were you able to read it back in from your new file, using a
new db object?

**Comment by jennykim1016** [comment]
Yes! I was just about to clean up all the notebooks and comment more, but it works.
<img width="1106" alt="screen shot 2017-02-08 at 5 14 06 pm" src="https://cloud.githubusercontent.com/assets/18297066/22764852/0db5b17e-ee22-11e6-8f62-8ba0f26da46f.png">

p.s: importing fits is an unnecessary line. I am going to erase it.

**Comment by drphilmarshall** [comment]
Super!

Also, nice screenshot - most helpful :-)
